FROM java:8-jdk-alpine
MAINTAINER Rodrigue Tchuensu P. <pouopse@yahoo.fr>

WORKDIR /app

COPY GradeManagementServer-0.0.1-SNAPSHOT.jar /app/GradeManagementServer-0.0.1-SNAPSHOT.jar

EXPOSE 9090

CMD ["java", "-jar", "GradeManagementServer-0.0.1-SNAPSHOT.jar"]